#!/usr/bin/env bash
# Regenerate GTK 3 / GTK 4 colours from the active Omarchy theme.
#
# Omarchy themes terminals, the shell, btop, helix, neovim and vscode, but has
# no template for GTK — so file managers and other GTK apps (Nautilus, Papers,
# GNOME dialogs) stay on stock Adwaita grey no matter which theme you run.
#
# Installed as a theme-set hook, this reads whichever theme is current and
# rewrites gtk.css to match, so GTK follows every theme rather than being
# pinned to one:
#
#     omarchy hook install theme-set tools/gtk-sync.sh
#
# Run it by hand to apply immediately. Remove the generated files to undo:
#     rm ~/.config/gtk-{3.0,4.0}/gtk.css
set -uo pipefail

COLORS="${1:-}"
[[ -f ${COLORS:-} ]] || COLORS="$HOME/.local/state/omarchy/current/theme/colors.toml"
[[ -f $COLORS ]] || { echo "no colors.toml at $COLORS" >&2; exit 1; }

read -r bg dbg ddbg lbg fg dfg accent selection muted red green orange <<<"$(
python3 - "$COLORS" <<'PY'
import re, sys
t = open(sys.argv[1]).read()
def g(key, fallback):
    m = re.search(r'^%s\s*=\s*"([^"]+)"' % re.escape(key), t, re.M)
    return m.group(1) if m else fallback
print(" ".join([
    g("background", "#1e1e2e"),      g("dark_background", "#181825"),
    g("darker_background", "#11111b"), g("lighter_background", "#313244"),
    g("foreground", "#cdd6f4"),      g("dark_foreground", "#9399b2"),
    g("accent", "#89b4fa"),          g("selection", "#45475a"),
    g("muted", "#585b70"),           g("red", "#f38ba8"),
    g("green", "#a6e3a1"),           g("orange", "#fab387"),
]))
PY
)"
[[ -n ${bg:-} ]] || { echo "could not parse colours" >&2; exit 1; }

gen_gtk4() {
  cat <<EOF
/* Generated by tools/gtk-sync.sh from the active Omarchy theme. Do not edit;
   it is rewritten on every theme change. Remove this file to fall back to
   stock Adwaita. */

@define-color window_bg_color $bg;
@define-color window_fg_color $fg;
@define-color view_bg_color $dbg;
@define-color view_fg_color $fg;

@define-color headerbar_bg_color $lbg;
@define-color headerbar_fg_color $fg;
@define-color headerbar_border_color $selection;
@define-color headerbar_backdrop_color $bg;
@define-color headerbar_shade_color rgba(0,0,0,0.36);

@define-color sidebar_bg_color $dbg;
@define-color sidebar_fg_color $fg;
@define-color sidebar_backdrop_color $bg;
@define-color sidebar_border_color $selection;
@define-color sidebar_shade_color rgba(0,0,0,0.30);
@define-color secondary_sidebar_bg_color $dbg;
@define-color secondary_sidebar_fg_color $fg;

@define-color card_bg_color $lbg;
@define-color card_fg_color $fg;
@define-color card_shade_color rgba(0,0,0,0.30);

@define-color dialog_bg_color $lbg;
@define-color dialog_fg_color $fg;
@define-color popover_bg_color $lbg;
@define-color popover_fg_color $fg;
@define-color popover_shade_color rgba(0,0,0,0.30);

@define-color accent_color $accent;
@define-color accent_bg_color $accent;
@define-color accent_fg_color $bg;

@define-color destructive_color $red;
@define-color destructive_bg_color $red;
@define-color destructive_fg_color $bg;
@define-color success_color $green;
@define-color success_bg_color $green;
@define-color success_fg_color $bg;
@define-color warning_color $orange;
@define-color warning_bg_color $orange;
@define-color warning_fg_color $bg;
@define-color error_color $red;
@define-color error_bg_color $red;
@define-color error_fg_color $bg;

@define-color borders $selection;
@define-color thumbnail_bg_color $lbg;
@define-color thumbnail_fg_color $fg;
@define-color shade_color rgba(0,0,0,0.32);
@define-color scrollbar_outline_color $selection;

/* Adwaita leaves a few surfaces on its own greys regardless of the named
   colours above; pin the ones a file manager actually shows. */
window, .background { background-color: $bg; color: $fg; }
headerbar, .titlebar { background-color: $lbg; color: $fg; }
.sidebar, .navigation-sidebar { background-color: $dbg; color: $fg; }
popover > contents, .popup > contents { background-color: $lbg; color: $fg; }
EOF
}

gen_gtk3() {
  cat <<EOF
/* Generated by tools/gtk-sync.sh from the active Omarchy theme. Do not edit. */

@define-color theme_bg_color $bg;
@define-color theme_fg_color $fg;
@define-color theme_base_color $dbg;
@define-color theme_text_color $fg;
@define-color theme_selected_bg_color $accent;
@define-color theme_selected_fg_color $bg;

@define-color insensitive_bg_color $bg;
@define-color insensitive_fg_color $muted;
@define-color insensitive_base_color $dbg;

@define-color theme_unfocused_bg_color $bg;
@define-color theme_unfocused_fg_color $dfg;
@define-color theme_unfocused_base_color $dbg;
@define-color theme_unfocused_text_color $fg;
@define-color theme_unfocused_selected_bg_color $selection;
@define-color theme_unfocused_selected_fg_color $fg;

@define-color borders $selection;
@define-color unfocused_borders $selection;
@define-color warning_color $orange;
@define-color error_color $red;
@define-color success_color $green;

@define-color wm_bg $lbg;
@define-color wm_title $fg;
@define-color menu_color $lbg;
@define-color popover_bg_color $lbg;
@define-color popover_fg_color $fg;
EOF
}

mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
gen_gtk4 >"$HOME/.config/gtk-4.0/gtk.css"
gen_gtk3 >"$HOME/.config/gtk-3.0/gtk.css"

# Dark variant + the theme's own icon set, so stock apps agree with the shell.
if command -v gsettings >/dev/null; then
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' 2>/dev/null
  gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark' 2>/dev/null
  icons="$HOME/.local/state/omarchy/current/theme/icons.theme"
  [[ -f $icons ]] && gsettings set org.gnome.desktop.interface icon-theme "$(<"$icons")" 2>/dev/null
fi

echo "GTK colours synced from $(basename "$(dirname "$COLORS")")"
